/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    copy: typeof import('./src/components/Index copy.vue')['default']
    Index: typeof import('./src/components/Index.vue')['default']
    Index1: typeof import('./src/components/menus/index1.vue')['default']
    Index2: typeof import('./src/components/menus/index2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
